import Link from 'next/link';
import { Media } from '@/components/media';
import { Arrow } from '@/components/identity';
import { BrandSignature } from '@/components/editorial';
import { pageMetadata } from '@/lib/site';
export const metadata = pageMetadata('Atölye', 'Kütahya’da bindallı, dikiş ve nakış. İplikten son ilmeğe, Yörem Çeyiz’in üretim dünyası.', '/atolye');
export default function AtelierPage() {
  return <><header className="page-heading dark-heading gutter"><p className="eyebrow">02 — ATÖLYE</p><h1>Ustalığın<br/><em>izinde.</em></h1><p>Her şey, bir ipliğin kumaşa değmesiyle başlar.</p></header><figure className="atelier-wide"><Media name="atelier" alt="Yörem Çeyiz atölyesinde nakış ve üretim masası" priority sizes="100vw"/><figcaption className="eyebrow gutter">İPLİKTEN BİNDALLIYA — ATÖLYE</figcaption></figure><section className="process-section section-space gutter"><p className="eyebrow">BİR BİNDALLININ YOLCULUĞU</p>{[{ image: 'collection/burgundy-table', title: 'Önce kumaş.', copy: 'Bordo kadife çalışma masasına serilir; motif, kesim ve malzeme aynı kompozisyonda buluşmaya başlar.' }, { image: 'needle-embroidery', title: 'Sonra ilmek.', copy: 'Nakışın ritmi, tekrar eden küçük hareketlerde saklıdır. Motif, çizgiden yüzeye geçer.' }, { image: 'collection/atelier-workroom', title: 'Ve bir atölye.', copy: 'Kalıp, kesim ve dikiş aynı mekânda birleşir. Ayrı parçalar bir silüete dönüşür; her detay bütündeki yerini bulur.' }].map((step, i) => <article className="process-row" key={step.title}><Media name={step.image} alt={step.title + ' Bindallı üretiminden görsel bir anlatım.'}/><div><span className="eyebrow">0{i + 1} / SÜREÇ</span><h2>{step.title}</h2><p>{step.copy}</p></div></article>)}</section><BrandSignature/><section className="collection-closing gutter"><h2>Bir fikirle <em>gelin.</em></h2><Link className="text-link" href="/iletisim">BİRLİKTE KONUŞALIM <Arrow/></Link></section></>;
}
